package com.sa.orm;

import com.sa.orm.util.StringUtils;

/**
 * <h4>Description</h4>Represents <code>long</code> data type field
 * criterion.
 * <h4>Copyrights</h4>Copyrights &copy; 2008 - 2012 Soft Assets.
 * All Rights Reserved.
 * <h4>Company</h4>Soft Assets
 * <h4>Created</h4>Feb 19, 2026
 * @author Ali Ahsan
 * @version 1.0
 */
public class SQLLongCriterion implements SQLCriterion {

  /**
   * Comparison operator
   */
  protected int operator = 0;

  /**
   * Name of the field which is to be compared
   */
  protected String fieldName = null;

  /**
   * Name of the table having the given field(column)
   */
  protected String tableName = null;

  /**
   * Values for comparison with the given field.
   */
  protected Long[] values = null;

  /**
   * Whether 'Or tableName.fieldName Is Null' to be appended to the 
   * criteria string generated by this class or not.
   */
  protected boolean compareNull = false;

  /**
   * Initializes the data members with the given values.
   * @param operator Comparison operator to compare the value against the given
   * field.
   * @param fieldName name of the field which is to be compared
   * @param tableName Name of the table having the given field(column)
   * @param values to compared for the given field.
   */
  public SQLLongCriterion(int operator, String fieldName, String tableName, Long[] values) {
    this(operator, fieldName, tableName, values, false);
  } // end of constructor

  /**
   * Initializes data members with the given values.
   * @param operator Comparison operator to compare the value against the given
   * field.
   * @param fieldName name of the field which is to be compared
   * @param tableName Name of the table having the given field(column)
   * @param values to compared for the given field.
   * @param compareNull Whether 'Or tableName.fieldName Is Null' to be
   * appended to the criteria string generated by this class or not.
   */
  public SQLLongCriterion(int operator, String fieldName, String tableName,
                         Long[] values, boolean compareNull) {

    this.operator = operator;
    this.fieldName = fieldName;
    this.tableName = tableName;
    this.values = values;
    this.compareNull = compareNull;
  } // end of constructor

  /**
   * Returns a string that can be used as criteria in 
   * <code>Where</code> clause of an SQL Statement
   * @return String to be used as a criterion in 
   * <code>Where</code> clause of an SQL statement.
   */
  public String getCriterionString() {
    StringBuffer criterionString = new StringBuffer("(");
    appendField(criterionString);
    criterionString.append(" ");
    switch(operator) {
      case EQUAL_TO:
        criterionString.append("= ");
        criterionString.append(values[0]);
        break;
      case NOT_EQUAL_TO:
        criterionString.append("<> ");
        criterionString.append(values[0]);
        break;
      case BETWEEN:
        criterionString.append("Between ");
        criterionString.append(values[0]);
        criterionString.append(" And ");
        criterionString.append(values[1]);
        break;
      case NOT_BETWEEN:
        criterionString.append("Not Between ");
        criterionString.append(values[0]);
        criterionString.append(" And ");
        criterionString.append(values[1]);
        break;
      case LESS_THAN:
        criterionString.append("< ");
        criterionString.append(values[0]);
        break;
      case LESS_THAN_EQUAL_TO:
        criterionString.append("<= ");
        criterionString.append(values[0]);
        break;
      case GREATER_THAN:
        criterionString.append("> ");
        criterionString.append(values[0]);
        break;
      case GREATER_THAN_EQUAL_TO:
        criterionString.append(">= ");
        criterionString.append(values[0]);
        break;
      case NULL:
        criterionString.append("Is Null");
        break;
      case NOT_NULL:
        criterionString.append("Is Not Null");
        break;
      case IN:
        criterionString.append("In (");
        criterionString.append(StringUtils.longArrayToString(values, ','));
        criterionString.append(")");
        break;
      case NOT_IN:
        criterionString.append("Not In (");
        criterionString.append(StringUtils.longArrayToString(values, ','));
        criterionString.append(")");
        break;
      default:
        break;
    } // end of switch
    if(this.compareNull == true) {
      criterionString.append(" Or ");
      appendField(criterionString);
      criterionString.append(" Is Null");
    } // end of if
    criterionString.append(")");
    return criterionString.toString();
  } // end of method getCriterionString

  /**
   * Appends the field name (and table name if present) to the given StringBuffer.
   * Can be overridden to apply wrapping/quoting.
   */
  protected void appendField(StringBuffer criterionString) {

    if(tableName != null && tableName.length() > 0) {
      criterionString.append(tableName);
      criterionString.append(".");
    } // end of if
    criterionString.append(fieldName);
  }

} // end of class SQLIntCriterion
