package com.sa.orm;

import com.sa.orm.util.StringUtils;

/**
 * <h4>Description</h4>Represents String data type field criterion.
 * <h4>Copyrights</h4>Copyrights &copy; 2008 - 2012 Soft Assets.
 * All Rights Reserved.
 * <h4>Company</h4>Soft Assets
 * <h4>Created</h4>October 27, 2008
 * @author Ali Ahsan
 * @version 1.0
 */
public class SQLStringCriterion implements SQLCriterion {

  /**
   * Comparison operator
   */
  protected int operator = 0;

  /**
   * Name of the field which is to be compared
   */
  protected String fieldName = null;

  /**
   * Name of the table having the given field(column)
   */
  protected String tableName = null;

  /**
   * Values for comparison with the given field.
   */
  protected String values[] = null;

  /**
   * Whether 'Or tableName.fieldName Is Null' to be appended to the
   * criteria string generated by this class or not
   */
  protected boolean compareNull = false;

  /**
   * Initializes the data members with the given values.
   * @param operator Comparison operator to compare the value against the given
   * field.
   * @param fieldName name of the field which is to be compared.
   * @param tableName Name of the table having the given field(column)
   * @param values to compared for the given field.
   */
  public SQLStringCriterion(int operator, String fieldName, String tableName,
                            String values[]) {

    this(operator, fieldName, tableName, values, false);
  } // end of constructor

  /**
   * Initializes the data members with the given values.
   * @param operator Comparison operator to compare the value against the given
   * field.
   * @param fieldName name of the field which is to be compared.
   * @param tableName Name of the table having the given field(column)
   * @param values to compared for the given field.
   * @param compareNull Whether 'Or tableName.fieldName Is Null' to be
   * appended to the criteria string generated by this class or not.
   */
  public SQLStringCriterion(int operator, String fieldName, String tableName,
                            String values[], boolean compareNull) {

    this.operator = operator;
    this.fieldName = fieldName;
    this.tableName = tableName;
    this.values = values;
    this.compareNull = compareNull;
  } // end of constructor

  /**
   * Returns a string that can be used as criteria in 
   * <code>Where</code> clause of an SQL Statement.
   * @return String that can be used as criteria in <code>Where</code>
   * clause of an SQL Statement
   */
  public String getCriterionString() {
    StringBuffer criterionString = new StringBuffer("(");
    boolean orFlag = false;
    boolean andFlag = false;

    appendField(criterionString);

    criterionString.append(" ");
    switch(operator) {
      case EQUAL_TO:
        criterionString.append("= '");
        criterionString.append(StringUtils.replaceCharacter(values[0], '\'', '`'));
        criterionString.append("'");
        break;
      case NOT_EQUAL_TO:
        criterionString.append("<> '");
        criterionString.append(StringUtils.replaceCharacter(values[0], '\'', '`'));
        criterionString.append("'");
        break;
      case NULL:
        criterionString.append(" Is Null");
        break;
      case NOT_NULL:
        criterionString.append(" Is Not Null");
        break;
      case IN:
        criterionString.append(" In (");
        for(int i = 0; i < values.length; i++) {
          if(i > 0) {
            criterionString.append(", ");
          } // end of if
          if(values[i] == null) {
            orFlag = true;
            if(i > 0) {
              criterionString.setLength(criterionString.toString().length() - 2);
            } // end of if
          } // end of if
          else {
            criterionString.append("'");
            criterionString.append(StringUtils.replaceCharacter(values[i], '\'', '`'));
            criterionString.append("'");
          } // end of else
        } // end of for
        criterionString.append(")");
        if(orFlag) {
          criterionString.append(" Or ");
          appendField(criterionString);
          criterionString.append(" Is Null");
        } // end of if one or more of the elements of array are null
        break;
      case NOT_IN:
        criterionString.append(" Not In (");
        for(int i = 0; i < values.length; i++) {
          if(i > 0) {
            criterionString.append(", ");
          } // end of if
          if(values[i] == null) {
            andFlag = true;
            if(i > 0) {
              criterionString.setLength(criterionString.toString().length() - 2);
            } // end of if
          } // end of if
          else {
            criterionString.append("'");
            criterionString.append(StringUtils.replaceCharacter(values[i], '\'', '`'));
            criterionString.append("'");
          } // end of else
        } // end of for
        criterionString.append(")");
        if(andFlag) {
          criterionString.append(" And ");
          appendField(criterionString);
          criterionString.append(" Is Not Null");
        } // end of if one or more of the elements of array are null
        break;
      case CONTAINS:
        criterionString.append(" Like '%");
        criterionString.append(StringUtils.replaceCharacter(values[0], '\'', '`'));
        criterionString.append("%'");
        break;
      case DOES_NOT_CONTAIN:
        criterionString.insert(1, "Not ");
        criterionString.append(" Like '%");
        criterionString.append(StringUtils.replaceCharacter(values[0], '\'', '`'));
        criterionString.append("%'");
        break;
      case STARTS_WITH:
        criterionString.append(" Like '");
        criterionString.append(StringUtils.replaceCharacter(values[0], '\'', '`'));
        criterionString.append("%'");
        break;
      case DOES_NOT_START_WITH:
        criterionString.insert(1, "Not ");
        criterionString.append(" Like '");
        criterionString.append(StringUtils.replaceCharacter(values[0], '\'', '`'));
        criterionString.append("%'");
        break;
      case ENDS_WITH:
        criterionString.append(" Like '%");
        criterionString.append(StringUtils.replaceCharacter(values[0], '\'', '`'));
        criterionString.append("'");
        break;
      case DOES_NOT_END_WITH:
        criterionString.insert(1, "Not ");
        criterionString.append(" Like '%");
        criterionString.append(StringUtils.replaceCharacter(values[0], '\'', '`'));
        criterionString.append("'");
        break;
      default:
        break;
    } // end of switch
    if(this.compareNull == true) {
      criterionString.append(" Or ");
      appendField(criterionString);
      criterionString.append(" Is Null");
    } // end of if
    criterionString.append(")");
    return criterionString.toString();
  } // end of method getCriterionString

  /**
   * Appends the field name (and table name if present) to the given StringBuffer.
   * Can be overridden to apply wrapping/quoting.
   */
  public void appendField(StringBuffer criterionString) {

    if(tableName != null && tableName.length() > 0) {
      criterionString.append(tableName);
      criterionString.append(".");
    } // end of if
    criterionString.append(fieldName);
  }
} // end of class SQLStringCriterion
