package com.sa.orm;

import com.sa.orm.util.StringUtils;

/**
 * <h4>Description</h4>Represents sub query type field criterion.
 * <h4>Copyrights</h4>Copyrights &copy; 2006 - 2012 Soft Assets.
 * All Rights Reserved.
 * <h4>Company</h4>Soft Assets
 * <h4>Created</h4>August 25, 2009
 * @author Ali Ahsan
 * @version 1.0
 */
public class SQLSubQueryCriterion implements SQLCriterion {

  /**
   * Comparison operator
   */
  protected int operator = 0;

  /**
   * Name of the field which is to be compared
   */
  protected String fieldName = null;

  /**
   * Name of the table having the given field(column)
   */
  protected String tableName = null;

  /**
   * Sub query for comparison with the given field.
   */
  protected String subQuery = null;

  /**
   * Mask to be applied on database field.
   */
  protected String dbMask = null;

  /**
   * Whether 'Or tableName.fieldName Is Null' to be appended to the 
   * criteria string generated by this class or not.
   */
  protected boolean compareNull = false;

  /**
   * Initializes the data members with the given values.
   * @param operator Comparison operator to compare the value against the given
   * field.
   * @param fieldName Name of the field which is to be compared
   * @param tableName Name of the table having the given field(column)
   * @param subQuery to be compared with the given field.
   */
  public SQLSubQueryCriterion(int operator, String fieldName, String tableName, String subQuery) {
    this(operator, fieldName, tableName, subQuery, false);
  } // end of constructor

  /**
   * Initializes data members with the given values.
   * @param operator Comparison operator to compare the value against the given
   * field.
   * @param fieldName Name of the field which is to be compared
   * @param tableName Name of the table having the given field(column)
   * @param subQuery to be compared with the given field.
   * @param compareNull Whether 'Or tableName.fieldName Is Null' to be
   * appended to the criteria string generated by this class or not.
   */
  public SQLSubQueryCriterion(int operator, String fieldName, String tableName,
      String subQuery, boolean compareNull) {

    this.operator = operator;
    this.fieldName = fieldName;
    this.tableName = tableName;
    this.subQuery = subQuery;
    this.compareNull = compareNull;
  } // end of constructor

  /**
   * Initializes data members with the given values.
   * @param operator Type of SQL comparison operator.
   * @param fieldName Name of the column that is to be compared with sub query.
   * @param tableName Name of the table having the given column
   * <code>fieldName</code>.
   * @param subQueryField Column to be included in sub query.
   * @param subQueryTable Table to be included in sub query.
   * @param dbMask Mask to be applied to column <code>subQueryField</code> in
   * case the <code>subQueryField</code> is compatible with Date types.
   * @param criteria {@link SQLCriterion} child class objects to generate
   * <code>Where</code> clause of the sub query.
   * @param booleanOperator Database AND / OR operator to be used between
   * <code>criteria</code>.
   * @param compareNull Whether 'Or tableName.fieldName Is Null' to be
   * appended to the criteria string generated by this class or not.
   */
  public SQLSubQueryCriterion(int operator, String fieldName, String tableName,
      String subQueryField, String subQueryTable, String dbMask,
      SQLCriterion[] criteria, BOOLEAN_OPERATOR booleanOperator, boolean compareNull) {

    this.operator = operator;
    this.fieldName = fieldName;
    this.tableName = tableName;
    this.subQuery = createSubQuery(subQueryField, subQueryTable, dbMask, criteria, booleanOperator);
    this.compareNull = compareNull;
    this.dbMask = dbMask;
  } // end of constructor

  /**
   * Creates an SQL statement for the given table <code>tableName</code>, column
   * <code>fieldName</code>, <code>criteria</code> and <code>operator</code>
   * that can be used as sub query in another query.
   * @param fieldName Column name to be included in the sub query.
   * @param tableName Table name whom column <code>fieldName</code> belongs to.
   * @param dbMask Mask to be applied to column in case the column is compatible
   * with Date types.
   * @param criteria Class to generate <code>Where</code> clause to be appended
   * to sub query.
   * @param booleanOperator Database AND / OR operator to be used between
   * <code>criteria</code>.
   * @return SQL query.
   */
  protected String createSubQuery(String fieldName, String tableName, String dbMask,
      SQLCriterion[] criteria, BOOLEAN_OPERATOR booleanOperator) {
    StringBuffer qry = new StringBuffer(ORMInfoManager.sqlConstantsObj.getClauseSelect());
    if(dbMask != null && dbMask.trim().length() > 0) {
      qry.append("Str_To_Date(Date_Format(");
      qry.append(fieldName);
      qry.append(", '");
      qry.append(dbMask);
      qry.append("') ");
      qry.append(", '");
      qry.append(dbMask);
      qry.append("') ");
    } // end of if
    else {
      qry.append(fieldName);
      qry.append(" ");
    } // end of else
    
    qry.append(ORMInfoManager.sqlConstantsObj.getClauseFrom());
    qry.append(tableName);
    qry.append(" ");
    
    if(criteria != null && criteria.length > 0) {
      qry.append(ORMInfoManager.sqlConstantsObj.getClauseWhere());
      qry.append(ORMInfoManager.sqlCriterionFactory.createCriteriaString(criteria, booleanOperator));
    } // end of if

    return qry.toString();
  } // end of method createSubQuery
  
  /**
   * Returns a string that can be used as criteria in 
   * <code>Where</code> clause of an SQL Statement
   * @return String to be used as a criterion in 
   * <code>Where</code> clause of an SQL statement.
   */
  public String getCriterionString() {
    StringBuffer criterionString = new StringBuffer("(");
    if(StringUtils.getNull(dbMask) != null) {
      criterionString.append("(Str_To_Date(Date_Format(");
      if(tableName != null && tableName.length() > 0) {
        criterionString.append(tableName);
        criterionString.append(".");
      } // end of if
      criterionString.append(fieldName);
      criterionString.append(", '");
      criterionString.append(dbMask);
      criterionString.append("')");
      criterionString.append(", '");
      criterionString.append(dbMask);
      criterionString.append("')");
    } // end of if
    else {
      if(tableName != null && tableName.length() > 0) {
        criterionString.append(tableName);
        criterionString.append(".");
      } // end of if
      criterionString.append(fieldName);
    } // end of else
    criterionString.append(" ");
    switch(operator) {
      case EQUAL_TO:
        criterionString.append("= (");
        criterionString.append(subQuery);
        criterionString.append(")");
        break;
      case NOT_EQUAL_TO:
        criterionString.append("<> (");
        criterionString.append(subQuery);
        criterionString.append(")");
        break;
      case LESS_THAN:
        criterionString.append("< (");
        criterionString.append(subQuery);
        criterionString.append(")");
        break;
      case LESS_THAN_EQUAL_TO:
        criterionString.append("<= (");
        criterionString.append(subQuery);
        criterionString.append(")");
        break;
      case GREATER_THAN:
        criterionString.append("> (");
        criterionString.append(subQuery);
        criterionString.append(")");
        break;
      case GREATER_THAN_EQUAL_TO:
        criterionString.append(">= (");
        criterionString.append(subQuery);
        criterionString.append(")");
        break;
      case IN:
        criterionString.append("In (");
        criterionString.append(subQuery);
        criterionString.append(")");
        break;
      case NOT_IN:
        criterionString.append("Not In (");
        criterionString.append(subQuery);
        criterionString.append(")");
        break;
      default:
        break;
    } // end of switch
    if(this.compareNull == true) {
      criterionString.append(" Or ");
      if(tableName != null && tableName.length() > 0) {
        criterionString.append(tableName);
        criterionString.append(".");
      } // end of if
      criterionString.append(fieldName);
      criterionString.append(" Is Null");
    } // end of if
    criterionString.append(")");
    return criterionString.toString();
  } // end of method getCriterionString

} // end of class SQLSubQueryCriterion
