package com.sa.orm;

import java.sql.Timestamp;

import com.sa.orm.util.DateUtils;
import com.sa.orm.util.StringUtils;

/**
 * <h4>Description</h4>Represents int data type field criterion.
 * <h4>Copyrights</h4>Copyrights &copy; 2008 - 2012 Soft Assets.
 * All Rights Reserved.
 * <h4>Company</h4>Soft Assets
 * <h4>Created</h4>October 27,2008
 * @author Ali Ahsan
 * @version 1.0
 */
public class SQLTimeStampCriterion implements SQLCriterion {

  /**
   * Type of SQL comparison operator
   */
  protected int operator = 0;

  /**
   * Name of the field which is to be compared
   */
  protected String fieldName = null;

  /**
   * Name of the table having the given field(column)
   */
  protected String tableName = null;

  /**
   * Values for comparison with the given field.
   */
  protected Timestamp values[] = null;

  /**
   * Format of the date to be used in SQL Expression (database
   * readable).
   */
  protected String dbMask = null;

  /**
   * Format of the date to be used in formatting the {@link Timestamp} object.
   */
  protected String javaMask = null;

  /**
   * Whether 'Or tableName.fieldName Is Null' to be appended to the
   * criteria string generated by this class or not.
   */
  protected boolean compareNull = false;

  /**
   * Initializes the data members with the given values.
   * @param operator Comparison operator to compare the value against the given
   * field.
   * @param fieldName Name of table column that is to be compared 
   * against the given value.
   * @param tableName Name of table having the given field.
   * @param values Array of {@link Timestamp} objects containing values to be 
   * compared.
   * @param dbMask Mask for the date value to be used in SQL query.
   * @param javaMask Mask for the date value to be used in java.
   */
  public SQLTimeStampCriterion(int operator, String fieldName, String tableName,
                               Timestamp values[], String dbMask, String javaMask) {

    this(operator, fieldName, tableName, values, dbMask, javaMask, false);
    if(StringUtils.getNull(javaMask) == null) {
      throw new IllegalArgumentException("javaMask is required.");
    } // end of if
  } // end of constructor

  /**
   * Initializes the data members with the given values.
   * @param operator Comparison operator to compare the value against the given
   * field.
   * @param fieldName Name of table column that is to be compared against the
   * given value.
   * @param tableName Name of table having the given field.
   * @param values Array of {@link Timestamp} objects containing values to be
   * compared.
   * @param dbMask Mask for the date value to be used in SQL query.
   * @param javaMask Mask for the date value to be used in java.
   * @param compareNull Whether the SQL where clause for the given field should
   * also contain the comparison of the field with <code>null</code> values.
   */
  public SQLTimeStampCriterion(int operator, String fieldName, String tableName,
                               Timestamp values[], String dbMask, String javaMask,
                               boolean compareNull) {

    if(StringUtils.getNull(javaMask) == null) {
      throw new IllegalArgumentException("javaMask is required.");
    } // end of if
    this.operator = operator;
    this.fieldName = fieldName;
    this.tableName = tableName;
    this.values = values;
    this.dbMask = dbMask;
    this.javaMask = javaMask;
    this.compareNull = compareNull;
  } // end of constructor

  /**
   * Wraps the given <code>fieldName</code> in respective functions to format
   * the value of the <code>fieldName</code> if <code>dbMask</code> is not
   * <code>null</code>.
   * @param fieldName Column name of the Date or related types.
   * @param tableName Name of the table whom <code>fieldName</code> belongs to.
   * @param dbMask Mask to format value of the <code>fieldName</code>.
   * @return String to be included in SQL query.
   */
  protected String wrapFieldInMasks(String fieldName, String tableName, String dbMask) {
    StringBuffer str = new StringBuffer("");
    if(StringUtils.getNull(dbMask) != null) {
      str.append("(Str_To_Date(Date_Format(");
      if(tableName != null && tableName.length() > 0) {
        str.append(tableName);
        str.append(".");
      } // end of if
      str.append(fieldName);
      str.append(", '");
      str.append(dbMask);
      str.append("')");
      str.append(", '");
      str.append(dbMask);
      str.append("')");
    } // end of if
    else {
      if(tableName != null && tableName.length() > 0) {
        str.append(tableName);
        str.append(".");
      } // end of if
      str.append(fieldName);
    } // end of else
    return str.toString();
  } // end of method wrapFieldInMasks
  
  /**
   * Wraps the given <code>value</code> in respective date format functions, if
   * <code>dbMask</code> is not <code>null</code> after formatting it with the
   * given <code>javaMask</code>.
   * @param value {@link Timestamp} value to be formatted and wrapped in
   * respective date format functions.
   * @param dbMask Mask to be used to format given <code>value</code> in
   * database.
   * @param javaMask Mask to format the given <code>value</code> before wrapping
   * it in respective date format functions.
   * @return String to be used in SQL query.
   */
  protected String wrapValueInMasks(Timestamp value, String dbMask, String javaMask) {
    StringBuffer str = new StringBuffer();
    String timestampValue = DateUtils.getDateToString(value, javaMask);
    if(StringUtils.getNull(dbMask) != null) {
      str.append("Str_To_Date('");
      str.append(timestampValue);
      str.append("', '");
      str.append(dbMask);
      str.append("')");
    } // end of if
    else {
      str.append("'");
      str.append(timestampValue);
      str.append("'");
    } // end of else
    return str.toString();
  } // end of method wrapValueInMasks
  
  /**
   * Returns a string that can be used as criteria in 
   * <code>Where</code> clause of an SQL Statement.
   * @return String that can be used as criteria in <code>Where</code>
   * clause of an SQL Statement.
   */
  public String getCriterionString() {
    StringBuffer criterionString = new StringBuffer("(");
    criterionString.append(wrapFieldInMasks(fieldName, tableName, dbMask));
    boolean orFlag = false;
    boolean andFlag = false;
    switch(operator) {
      case EQUAL_TO:
        criterionString.append(" = ");
        criterionString.append(wrapValueInMasks(values[0], dbMask, javaMask));
        break;
      case NOT_EQUAL_TO:
        criterionString.append(" <> ");
        criterionString.append(wrapValueInMasks(values[0], dbMask, javaMask));
        break;
      case NOT_BETWEEN:
        criterionString.append(" Not Between ");
        criterionString.append(wrapValueInMasks(values[0], dbMask, javaMask));
        criterionString.append(" And ");
        criterionString.append(wrapValueInMasks(values[1], dbMask, javaMask));
        break;
      case BETWEEN:
        criterionString.append(" Between ");
        criterionString.append(wrapValueInMasks(values[0], dbMask, javaMask));
        criterionString.append(" And ");
        criterionString.append(wrapValueInMasks(values[1], dbMask, javaMask));
        break;
      case LESS_THAN:
        criterionString.append(" < ");
        criterionString.append(wrapValueInMasks(values[0], dbMask, javaMask));
        break;
      case LESS_THAN_EQUAL_TO:
        criterionString.append(" <= ");
        criterionString.append(wrapValueInMasks(values[0], dbMask, javaMask));
        break;
      case GREATER_THAN:
        criterionString.append(" > ");
        criterionString.append(wrapValueInMasks(values[0], dbMask, javaMask));
        break;
      case GREATER_THAN_EQUAL_TO:
        criterionString.append(" >= ");
        criterionString.append(wrapValueInMasks(values[0], dbMask, javaMask));
        break;
      case NULL:
        criterionString.append(" Is Null");
        break;
      case NOT_NULL:
        criterionString.append(" Is Not Null");
        break;
      case IN:
        criterionString.append(" In (");
        for(int i = 0; i < values.length; i++) {
          if(i > 0) {
            criterionString.append(", ");
          }
          if(values[i] == null) {
            orFlag = true;
            if(i > 0) {
              criterionString.setLength(criterionString.toString().length() - 2);
            } // end of if
          }
          else {
            criterionString.append(wrapValueInMasks(values[i], dbMask, javaMask));
          } // end of else

        } // end of for
        criterionString.append(")");
        if(orFlag) {
          criterionString.append(" Or ");
          if(tableName != null && tableName.length() > 0) {
            criterionString.append(tableName);
            criterionString.append(".");
          } // end of if
          criterionString.append(fieldName);
          criterionString.append(" Is Null");
        } // end of if one or more of the elements of array are null
        break;
      case NOT_IN:
        criterionString.append(" Not In (");
        for(int i = 0; i < values.length; i++) {
          if(i > 0) {
            criterionString.append(", ");
          }
          if(values[i] == null) {
            andFlag = true;
            if(i > 0) {
              criterionString.setLength(criterionString.toString().length() - 2);
            } // end of if
          }
          else {
            criterionString.append(wrapValueInMasks(values[i], dbMask, javaMask));
          } // end of else

        } // end of for
        criterionString.append(")");
        if(andFlag) {
          criterionString.append(" And ");
          if(tableName != null && tableName.length() > 0) {
            criterionString.append(tableName);
            criterionString.append(".");
          } // end of if
          criterionString.append(fieldName);
          criterionString.append(" Is Not Null");
        } // end of if one or more of the elements of array are null
        break;
      default:
        break;
    } // end of switch
    if(this.compareNull == true) {
      criterionString.append(" Or ");
      if(tableName != null && tableName.length() > 0) {
        criterionString.append(tableName);
        criterionString.append(".");
      } // end of if
      criterionString.append(fieldName);
      criterionString.append(" Is Null");
    } // end of if
    criterionString.append(")");
    return criterionString.toString();
  } // end of method getCriterionString

} // end of class SQLTimeStampCriterion
