--liquibase formatted sql

--changeset zyre:1

CREATE TABLE "UserType" (
    "id" INT NOT NULL,
    "label" VARCHAR(15) NOT NULL,
    CONSTRAINT "pk_UserType" PRIMARY KEY ("id")
);
INSERT INTO "UserType" ("id", "label") VALUES
(1, 'System'),
(2, 'BackOffice'),
(3, 'Firm'),
(4, 'Client Portal');

CREATE TABLE "User" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "firstName" VARCHAR(50) NOT NULL,
    "lastName" VARCHAR(50) NOT NULL,
    "middleName" VARCHAR(50),
    "email" VARCHAR(100) NOT NULL,
    "homePhone" VARCHAR(25),
    "cellPhone" VARCHAR(25),
    "timezone" VARCHAR(50) DEFAULT 'America/New_York' NOT NULL,
    "dateFormat" VARCHAR(50) DEFAULT 'MM/DD/YYYY' NOT NULL,
    "lastSuccessfulLogin" TIMESTAMP WITHOUT TIME ZONE,
    "failedLoginAttempts" INT DEFAULT 0,
    "lastLoginAttempt" TIMESTAMP WITHOUT TIME ZONE,
    "externalId" VARCHAR(250),
    "sessionTimeoutMinutes" INT DEFAULT 30 NOT NULL,
    "isActive" BOOLEAN DEFAULT TRUE,
    "userTypeId" INT NOT NULL,
    "createdByUserId" INT,
    "createdAt" TIMESTAMP WITHOUT TIME ZONE,
    "updatedAt" TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT "pk_User" PRIMARY KEY ("id"),
    CONSTRAINT "uc_User_email" UNIQUE ("email"),
    CONSTRAINT "fk_UserType_userTypeId_id" FOREIGN KEY ("userTypeId") REFERENCES "UserType" ("id")
);
ALTER TABLE "User" ADD CONSTRAINT "fk_User_createdByUserId_id" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id");

CREATE TABLE "UserCredentials" (
    "userId" INT NOT NULL,
    "username" VARCHAR(100),
    "password" VARCHAR(250),
    CONSTRAINT "pk_UserCredentials" PRIMARY KEY ("userId"),
    CONSTRAINT "uc_UserCredentials_username" UNIQUE ("username")
);
ALTER TABLE "UserCredentials" ADD CONSTRAINT "fk_UserCredentials_id_userId" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE;

INSERT INTO "User" ("firstName", "lastName", "email", "userTypeId")
VALUES 
('System', 'Admin', 'zyre.time.billing#1@gmail.com', 1),
('Backoffice', 'Admin', 'zyre.time.billing@gmail.com', 2),
('Backoffice', 'User', 'zyre.time.billing#2@gmail.com', 2),
('John', 'Doe', 'john.doe@example.com', 3),
('Jane', 'Smith', 'jane.smith@example.com', 3);

INSERT INTO "UserCredentials" ("userId", "username", "password")
VALUES
(1, 'sysadmin', '$2a$10$PfjC.SBJhAscEpP7f2wcrO/QkiFsTC1s9ZdIna32euMk5NJXn2FoW'), -- password $ysAdminP@ssw0rd
(2, 'backofficeAdmin', '$2a$10$UBWkzHnjLgbADWiHeSz9Fetq6IbzvjFsC.o6H2KWDgs/XwWWRkhNe'), -- B0AdminP@ssw0rd
(3, 'backofficeUser', '$2a$10$YlcnCEh9Z1TwgmPrsK9dmO7ONje6M42Ar5BNraQn6Y.RlvULNE23.'), -- B0U$erPa$$w0rd
(4, 'johndoe', '$2a$10$kwYwAHFL4.1jFJo/ui.xxeuJvDKM/PoiYNjuyDN5lBcEhbH1YnzlO'), -- F1rmAdminP@ss
(5, 'janesmith', '$2a$10$mwR38c12vHomf2534z0Zgu/K4UalAY7V9IJiZoGfagpsWhlDA9hDW'); -- F1rmUserP@S$

CREATE TABLE "FirmUser" (
    "userId" INT NOT NULL, -- FK
    "title" VARCHAR(10),
    "SSN" VARCHAR(50),
    "isOwner" BOOLEAN DEFAULT FALSE NOT NULL,
    "loginCount" INT,
    "verificationCode" VARCHAR(255),
    "lastUpdatedBy" INT, -- FK
    "updatedAt" TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT "pk_FirmUser" PRIMARY KEY ("userId"),
    CONSTRAINT "fk_FirmUser_userId_id" FOREIGN KEY ("userId") REFERENCES "User" ("id"),
    CONSTRAINT "fk_FirmUser_lastUpdatedBy_id" FOREIGN KEY ("lastUpdatedBy") REFERENCES "User" ("id")
);
COMMENT ON COLUMN "FirmUser"."loginCount" IS 'Total number of successful log-ins for this user';
