package com.sa.orm.pgsql.v4;

import com.sa.orm.util.StringUtils;

/**
 * <h4>Description</h4>Represents <code>double</code> data type field
 * criterion.
 * <h4>Copyrights</h4>Copyrights &copy; 2008 - 2012 Soft Assets.
 * All Rights Reserved.
 * <h4>Company</h4>Soft Assets
 * <h4>Created</h4>Feb 19, 2026
 * @author Ali Ahsan
 * @version 1.0
 */
public class SQLDoubleCriterion extends com.sa.orm.SQLDoubleCriterion {

  /**
   * Initializes the data members with the given values.
   * @param operator Comparison operator to compare the value against the given
   * field.
   * @param fieldName name of the field which is to be compared
   * @param tableName Name of the table having the given field(column)
   * @param values to compared for the given field.
   */
  public SQLDoubleCriterion(int operator, String fieldName, String tableName, Double[] values) {
    super(operator, fieldName, tableName, values);
  } // end of constructor

  /**
   * Initializes data members with the given values.
   * @param operator Comparison operator to compare the value against the given
   * field.
   * @param fieldName name of the field which is to be compared
   * @param tableName Name of the table having the given field(column)
   * @param values to compared for the given field.
   * @param compareNull Whether 'Or tableName.fieldName Is Null' to be
   * appended to the criteria string generated by this class or not.
   */
  public SQLDoubleCriterion(int operator, String fieldName, String tableName,
      Double[] values, boolean compareNull) {
    super(operator, fieldName, tableName, values, compareNull);
  } // end of constructor

  @Override
  protected void appendField(StringBuffer criterionString) {
    criterionString.append(StringUtils.wrapDBField(tableName, fieldName, SQLConstants.FIELD_PREFIX, SQLConstants.FIELD_SUFFIX, SQLConstants.QUALIFIER_SEPARATOR));
  }

} // end of class SQLDoubleCriterion
