package com.sa.orm.mysql.v5_0;

import com.sa.orm.util.StringUtils;

/**
 * <h4>Description</h4>Represents <code>boolean</code> data type field
 * criterion.
 * <h4>Copyrights</h4>Copyrights &copy; 2008 - 2026 Soft Assets.
 * All Rights Reserved.
 * <h4>Company</h4>Soft Assets
 * <h4>Created</h4>April 11, 2026
 * @author Ali Ahsan
 * @version 1.0
 */
public class SQLBooleanCriterion extends com.sa.orm.SQLBooleanCriterion {

  /**
   * Initializes the data members with the given values.
   * @param operator Comparison operator to compare the value against the given
   * field.
   * @param fieldName name of the field which is to be compared
   * @param tableName Name of the table having the given field(column)
   * @param values to compared for the given field.
   */
  public SQLBooleanCriterion(int operator, String fieldName, String tableName, Boolean[] values) {
    super(operator, fieldName, tableName, values);
  } // end of constructor

  /**
   * Initializes data members with the given values.
   * @param operator Comparison operator to compare the value against the given
   * field.
   * @param fieldName name of the field which is to be compared
   * @param tableName Name of the table having the given field(column)
   * @param values to compared for the given field.
   * @param compareNull Whether 'Or tableName.fieldName Is Null' to be
   * appended to the criteria string generated by this class or not.
   */
  public SQLBooleanCriterion(int operator, String fieldName, String tableName,
      Boolean[] values, boolean compareNull) {
    super(operator, fieldName, tableName, values, compareNull);
  } // end of constructor

} // end of class SQLBooleanCriterion
