package com.sa.orm.mysql.v5_0;

/**
 * <h4>Description</h4>Represents <code>float</code> data type field
 * criterion.
 * <h4>Copyrights</h4>Copyrights &copy; 2008 - 2012 Soft Assets.
 * All Rights Reserved.
 * <h4>Company</h4>Soft Assets
 * <h4>Created</h4>May 14, 2009
 * @author Ali Ahsan
 * @version 1.0
 */
public class SQLFloatCriterion extends com.sa.orm.SQLFloatCriterion {

  /**
   * Initializes the data members with the given values.
   * @param type Type of sql comparison operator.
   * @param fieldName name of the field which is to be compared.
   * @param tableName Name of the table having the given field(column)
   * @param values to compared for the given field.
   */
  public SQLFloatCriterion(int type, String fieldName, String tableName, Float[] values) {
    super(type, fieldName, tableName, values);
  } // end of constructor

  /**
   * Initializes data members with the given values.
   * @param type Type of sql comparison operator.
   * @param fieldName name of the field which is to be compared.
   * @param tableName Name of the table having the given field(column)
   * @param values to compared for the given field.
   * @param compareNull Whether 'Or tableName.fieldName Is Null' to be
   * appended to the criteria string generated by this class or not.
   */
  public SQLFloatCriterion(int type, String fieldName, String tableName,
      Float[] values, boolean compareNull) {
    super(type, fieldName, tableName, values, compareNull);
  } // end of constructor

} // end of class SQLFloatCriterion
