package com.sa.orm.mysql.v5_0;

/**
 * <h4>Description</h4>Represents String data type field criterion.
 * <h4>Copyrights</h4>Copyrights &copy; 2008 - 2012 Soft Assets.
 * All Rights Reserved.
 * <h4>Company</h4>Soft Assets
 * <h4>Created</h4>October 27, 2008
 * @author Ali Ahsan
 * @version 1.0
 */
public class SQLStringCriterion extends com.sa.orm.SQLStringCriterion {

  /**
   * Initializes the data members with the given values.
   * @param type Type of sql comparison operator.
   * @param fieldName name of the field which is to be compared.
   * @param tableName Name of the table having the given field(column)
   * @param values to compared for the given field.
   */
  public SQLStringCriterion(int type, String fieldName, String tableName,
                            String values[]) {

    super(type, fieldName, tableName, values);
  } // end of constructor

  /**
   * Initializes the data members with the given values.
   * @param type Type of sql comparison operator.
   * @param fieldName name of the field which is to be compared.
   * @param tableName Name of the table having the given field(column)
   * @param values to compared for the given field.
   * @param compareNull Whether 'Or tableName.fieldName Is Null' to be
   * appended to the criteria string generated by this class or not.
   */
  public SQLStringCriterion(int type, String fieldName, String tableName,
                            String values[], boolean compareNull) {

    super(type, fieldName, tableName, values, compareNull);
  } // end of constructor

} // end of class SQLStringCriterion
