package com.sa.orm.mysql.v5_0;

import com.sa.orm.SQLCriterion;

/**
 * <h4>Description</h4>Represents sub query type field criterion.
 * <h4>Copyrights</h4>Copyrights &copy; 2006 - 2012 Soft Assets.
 * All Rights Reserved.
 * <h4>Company</h4>Soft Assets
 * <h4>Created</h4>August 25, 2009
 * @author Ali Ahsan
 * @version 1.0
 */
public class SQLSubQueryCriterion extends com.sa.orm.SQLSubQueryCriterion {

  /**
   * Initializes the data members with the given values.
   * @param type Type of SQL comparison operator
   * @param fieldName name of the field which is to be compared
   * @param tableName Name of the table having the given field(column)
   * @param subQuery to be compared with the given field.
   */
  public SQLSubQueryCriterion(int type, String fieldName, String tableName, String subQuery) {
    super(type, fieldName, tableName, subQuery);
  } // end of constructor

  /**
   * Initializes data members with the given values.
   * @param type Type of SQL comparison operator
   * @param fieldName name of the field which is to be compared
   * @param tableName Name of the table having the given field(column)
   * @param subQuery to be compared with the given field.
   * @param compareNull Whether 'Or tableName.fieldName Is Null' to be
   * appended to the criteria string generated by this class or not.
   */
  public SQLSubQueryCriterion(int type, String fieldName, String tableName,
                         String subQuery, boolean compareNull) {
    super(type, fieldName, tableName, subQuery, compareNull);
  } // end of constructor

  /**
   * Initializes data members with the given values.
   * @param type Type of SQL comparison operator.
   * @param fieldName Name of the column that is to be compared with sub query.
   * @param tableName Name of the table having the given column
   * <code>fieldName</code>.
   * @param subQueryField Column to be included in sub query.
   * @param subQueryTable Table to be included in sub query.
   * @param dbMask Mask to be applied to column <code>subQueryField</code> in
   * case the <code>subQueryField</code> is compatible with Date types.
   * @param criteria {@link SQLCriterion} child class objects to generate
   * <code>Where</code> clause of the sub query.
   * @param booleanOperator Database AND / OR operator to be used between
   * <code>criteria</code>.
   * @param compareNull Whether 'Or tableName.fieldName Is Null' to be
   * appended to the criteria string generated by this class or not.
   */
  public SQLSubQueryCriterion(int type, String fieldName, String tableName,
                         String subQueryField, String subQueryTable,
                         String dbMask, SQLCriterion[] criteria, BOOLEAN_OPERATOR booleanOperator,
                         boolean compareNull) {
     super(type, fieldName, tableName, subQueryField, subQueryTable, dbMask, criteria, booleanOperator, compareNull);
  } // end of constructor

} // end of class SQLSubQueryCriterion
